services:
  be:
    build:
      context: backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./backend/db.sqlite3:/app/db.sqlite3
      - ./backend/media:/app/media
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8000"]
      interval: 5s
      timeout: 15s
      retries: 3
    networks:
      - default
    develop:
      watch:
        - action: rebuild
          path: backend/manage.py
          target: /app/manage.py
        - action: rebuild
          path: backend/requirements.txt
          target: /app/requirements.txt
        - action: sync
          path: backend/docusecure
          target: /app/docusecure

  elasticsearch:
    image: elasticsearch
    ports:
      - 9200
      - 9300
    environment:
      - discovery.type=single-node
    networks:
      - default

networks:
  default:
