# providers:
#   docker:
#     exposedByDefault: false
#     watch: true
#     allowEmptyServices: true
#     network: docusecure
#     useBindPortIP: true
global:
  checkNewVersion: false
  sendAnonymousUsage: false
log:
  level: DEBUG
api:
  dashboard: true
  insecure: true
entryPoints:
  web:
    address: :80
  websecure:
    address: :443
