# Generated by Django 4.2.19 on 2025-03-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='title',
        ),
        migrations.AddField(
            model_name='doc',
            name='mimetype',
            field=models.CharField(default='text/plain', max_length=64),
            preserve_default=False,
        ),
    ]
